// copy from: https://grpc.io/docs/what-is-grpc/introduction/

syntax = "proto3";

// The greeter service definition.
service Test {
  // Sends a greeting
  rpc TestDeadline(DeadlineRequest) returns (TestReply) {}
  rpc TestStreamOut(StreamOutRequest) returns (stream StreamOutResponse)
}

// The request message containing the user's name.
message DeadlineRequest {
  int32 ms = 1;
}

// The response message containing the greetings
message TestReply {
  string message = 1;
}

message StreamOutRequest {
  optional string message = 1;
}

message StreamOutResponse {
  optional string message = 1;
}
